Feature/register login api
Tomas-Per/AutomatedDeliverySystem pull request #4
Opened 2022-05-01 16:44 UTC by Foteno

Added register, login, added hashing of passwords, added exceptions

2022-05-01 20:03 UTC, Tomas-Per requested changes

2022-05-01 20:03 UTC, Tomas-Per commented on Backend/src/main/java/lt/vu/ads/service/courier/CourierServiceImpl.java
> +            throw new WrongPasswordException("Neteisingas slaptažodis");
Messages should be in English preferably.

2022-05-01 20:03 UTC, Tomas-Per commented on Backend/src/main/java/lt/vu/ads/security/SecurityConfig.java
> +        return new BCryptPasswordEncoder();
Maybe change this to `return new BCryptPasswordEncoder(12);` (default strength is 10) for better security

2022-05-01 20:03 UTC, Tomas-Per commented on Backend/src/main/java/lt/vu/ads/service/user/UserServiceImpl.java
> +            throw new WrongPasswordException("Neteisingas slaptažodis");
English.

2022-05-01 20:09 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/service/courier/CourierServiceImpl.java
> +            throw new WrongPasswordException("Neteisingas slaptažodis");
agreed

2022-05-01 20:09 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/security/SecurityConfig.java
> +        return new BCryptPasswordEncoder();
agreed

2022-05-01 20:21 UTC, Tomas-Per approved these changes

2022-05-02 17:55 UTC, Filari02 commented
seems good

2022-05-02 17:55 UTC, Ugniusst approved these changes

2022-05-02 17:56 UTC, Filari02 approved these changes

2022-05-02 17:58 UTC, aule2000 approved these changes
Good

2022-05-02 18:02 UTC, merged