Feature/api structure update
Tomas-Per/AutomatedDeliverySystem pull request #5
Opened 2022-05-10 15:41 UTC by Foteno

Įvertinkite, ačiū.

2022-05-10 15:43 UTC, Tomas-Per approved these changes

2022-05-10 15:47 UTC, aule2000 requested changes

2022-05-10 15:47 UTC, aule2000 commented on Backend/src/main/java/lt/vu/ads/controllers/OrderController.java
> +    public ResponseEntity<Order> updateOrderd(@PathVariable(value = "id") Long orderId,
Maybe there should be an updateOrder?

2022-05-10 16:03 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/controllers/OrderController.java
> +    public ResponseEntity<Order> updateOrderd(@PathVariable(value = "id") Long orderId,
oops

2022-05-10 16:05 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/controllers/OrderController.java
> +    public ResponseEntity<Order> updateOrderd(@PathVariable(value = "id") Long orderId,
I fixed it with 2nd commit, please check Files changed tab

2022-05-10 16:06 UTC, Filari02 approved these changes

2022-05-10 18:49 UTC, aule2000 requested changes

2022-05-10 18:49 UTC, aule2000 commented on Backend/src/main/java/lt/vu/ads/exceptions/ExceptionController.java
>      private static final String UNKNOWN_SERVER_ERROR_RESPONSE_MESSAGE = "Nežinoma serverio klaida";
Maybe you should write unknown server error message in english

2022-05-11 12:31 UTC, aule2000 approved these changes

2022-05-11 12:43 UTC, Tomas-Per commented on Backend/src/main/java/lt/vu/ads/controllers/OrderController.java
> +    public Order ecreateOrder(@RequestBody Order order) {
typo here probably

2022-05-12 10:16 UTC, Ugniusst approved these changes

2022-05-12 18:18 UTC, merged