Price Calculator API
Tomas-Per/AutomatedDeliverySystem pull request #9
Opened 2022-05-14 14:28 UTC by aule2000

Updated price calculation feature

2022-05-14 14:38 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/controllers/PriceController.java
> +    public double getPrice(@RequestBody Order order) {
Now we should use views, if a field is missing, add it to the view

2022-05-14 14:43 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/models/order/json/OrderView.java
> +    private Address destinationAddress;
Should use views(dtos), and if full address is not always needed when returning this view, should return just id, that could be used to get address by id afterwards

2022-05-15 23:54 UTC, Tomas-Per approved these changes

2022-05-16 12:20 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/service/order/utils/DistanceCalculator.java
> +    public double  calculateDistance(AddressView sourceAddress, AddressView destinationAddress) {
double whitespace

2022-05-16 12:25 UTC, Foteno commented on Backend/src/main/java/lt/vu/ads/service/order/OrderServiceImpl.java
> +        Order order = new Order();
Doesn't look good, either create some other DTO, or at least instead of creating new Order entity here and later converting it to OrderView, create a new OrderView object and set its estimatedArrival and price fields

2022-05-16 12:26 UTC, Foteno requested changes
creating new order, setting its fields and converting to DTO should be fixed

2022-05-16 20:33 UTC, Ugniusst approved these changes

2022-05-18 17:10 UTC, merged